variables:
  - name: Version.MajorMinor
    value: 1
  - name: Version.Revision
    value: $[counter(variables['Version.MajorMinor'], 0)]
  - group: AWS_Credentials
  - group: environment-itaap-dev
name: $(Version.MajorMinor).$(Version.Revision)
resources:
  repositories:
    - repository: self
      type: GitHub
      name: philips-internal/itaap-common-demand-intake-ui
      connection: philips-internal
      pr:
        branches:
          include:
            - main
        paths:
          exclude:
            - README.md
            - .gitignore
            - azure-pipeline.yaml
            - azure-pipeline-CD.yaml
      trigger:
        branches:
          include:
            - main
        paths:
          exclude:
            - README.md
            - .gitignore
            - azure-pipeline.yaml
            - azure-pipeline-CD.yaml
pool:
  vmImage: ubuntu-latest
stages:
  - stage: Build
    displayName: Build job
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 18.x
            displayName: Install Node.js
          - task: Docker@2
            condition: and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
          - template: docker-build-push.yaml
            parameters:
              ImageName: itaap-common-demand-intake-ui
              AddImageTag: $(Version.MajorMinor).$(Version.Revision)
              Registry: 762168133611.dkr.ecr.eu-west-1.amazonaws.com/itaap
              Namespace: common
              Dockerfile: "Dockerfile"
