apiVersion: apps/v1
kind: Deployment
metadata:
  name: itaap-common-demand-intake-ui-deployment
  namespace: {{deployNamespace}}
  labels:
    app: itaap-common-demand-intake-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itaap-common-demand-intake-ui
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: itaap-common-demand-intake-ui
    spec:
      containers:
        - name: itaap-common-demand-intake-ui-container
          image: >-
            762168133611.dkr.ecr.eu-west-1.amazonaws.com/itaap/common/itaap-common-demand-intake-ui:{{imageTagName}}
          env:
            - name: ENV_VAR
              value: {{env}}
          ports:
            - containerPort: 8080
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      restartPolicy: Always
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
apiVersion: v1
kind: Service
metadata:
  name: itaap-common-demand-intake-ui-service
  namespace: {{deployNamespace}}
  labels:
    app: itaap-common-demand-intake-ui
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: itaap-common-demand-intake-ui

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: itaap-common-demand-intake-ui-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
  namespace: {{deployNamespace}}
spec:
  defaultBackend:
    service:
      name: itaap-common-demand-intake-ui-service
      port:
        number: 80
  tls:
    - hosts:
        - {{host}}
      secretName: itaap-tls-secret
  rules:
    - host: {{host}}
      http:
        paths:
          - path: {{envIdentifier}}/demand-intake-ui
            pathType: Prefix
            backend:
              service:
                name: itaap-common-demand-intake-ui-service
                port:
                  number: 80

---