export enum DemandStatus {
  DRAFT = 'DRAFT',
  PENDING_WITH_DM = 'PENDING_WITH_DM',
  DM_HOLD = 'DM_HOLD',
  PENDING_WITH_CCB = 'PENDING_WITH_CCB',
  CCB_HOLD = 'CCB_HOLD',
  ACCEPTED = 'ACCEPTED',
  DM_REJECTED = 'DM_REJECTED',
  CCB_REJECTED = 'CCB_REJECTED',
  DM_MODIFICATION = 'DM_MODIFICATION',
  CCB_MODIFICATION = 'CCB_MODIFICATION'
}
